services:
  web:
    build: .
    container_name: django_app
    command: >
      sh -c "
        while ! nc -z db 3306; do
          echo 'Waiting for MySQL...';
          sleep 2;
        done;
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "


    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: ilwad/my-mysql-with-data:latest
    container_name: mysql_db
    ports:
      - "3302:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  static_volume:
  media_volume:
